-- Phase 38: 租户品牌配置默认数据
-- 为 tenant_id = 0 (系统默认租户) 创建默认品牌配置

INSERT INTO sys_tenant_brand (
    id,
    brand_name,
    logo_url,
    favicon_url,
    primary_color,
    secondary_color,
    background_color,
    login_bg_url,
    login_slogan,
    copyright_text,
    icp_number,
    footer_links,
    mobile_icon_url,
    mobile_splash_url,
    custom_css,
    tenant_id,
    created_by,
    created_time,
    updated_by,
    updated_time,
    deleted,
    version
) VALUES (
    1000000000000000001,
    'LJWX Platform',
    '/assets/logo.png',
    '/assets/favicon.ico',
    '#1890ff',
    '#52c41a',
    '#f0f2f5',
    '/assets/login-bg.jpg',
    '智能化企业管理平台',
    'Copyright © 2026 LJWX Platform. All rights reserved.',
    NULL,
    '[]'::jsonb,
    '/assets/mobile-icon.png',
    '/assets/mobile-splash.png',
    NULL,
    0,
    0,
    CURRENT_TIMESTAMP,
    0,
    CURRENT_TIMESTAMP,
    FALSE,
    1
);
