// Re-export all types
export type { Result, PageResult, PageQuery } from './api'
export type {
  LoginDTO,
  TokenVO,
  UserInfo,
  LoginVO,
  UserVO,
  UserRoleVO,
  UserQueryDTO,
  UserCreateDTO,
  UserUpdateDTO,
} from './user'
export type {
  PermissionVO,
  RoleVO,
  RoleQueryDTO,
  RoleCreateDTO,
  RoleUpdateDTO,
} from './role'
export type {
  TenantVO,
  TenantQueryDTO,
  TenantCreateDTO,
  TenantUpdateDTO,
  TenantFreezeDTO,
  TenantCancelDTO,
  SysDictTypeVO,
  SysDictDataVO,
  DictTypeQueryDTO,
  DictTypeCreateDTO,
  DictTypeUpdateDTO,
  SysConfigVO,
  ConfigQueryDTO,
  ConfigCreateDTO,
  ConfigUpdateDTO,
  SysJobVO,
  JobQueryDTO,
  JobCreateDTO,
  JobUpdateDTO,
  OperationLogVO,
  OperationLogQueryDTO,
  LoginLogVO,
  LoginLogQueryDTO,
  SysFileVO,
  FileQueryDTO,
  SysNoticeVO,
  NoticeQueryDTO,
  NoticeCreateDTO,
  NoticeUpdateDTO,
  ScreenOverviewVO,
  ScreenRealtimeVO,
  ScreenTrendItem,
  ScreenTrendVO,
  MenuVO,
  MenuTreeVO,
  MenuCreateDTO,
  MenuUpdateDTO,
} from './common'
