package com.ljwx.platform.phase05;

import com.ljwx.platform.app.test.base.BaseCrudTest;

import java.util.Map;
import java.util.UUID;

class RoleApiTest extends BaseCrudTest {

    @Override
    protected String basePath() {
        return "/api/roles";
    }

    @Override
    protected String listPermission() {
        return "role:read";
    }

    @Override
    protected String createPermission() {
        return "role:write";
    }

    @Override
    protected String updatePermission() {
        return "role:write";
    }

    @Override
    protected String deletePermission() {
        return "role:delete";
    }

    @Override
    protected Map<String, Object> createJson() {
        String suffix = UUID.randomUUID().toString().substring(0, 8);
        return Map.of(
                "name", "IT Role " + suffix,
                "code", "it_role_" + suffix,
                "description", "generated by integration test"
        );
    }

    @Override
    protected Map<String, Object> updateJson() {
        return Map.of(
                "name", "IT Role Updated",
                "description", "updated by integration test",
                "status", 1
        );
    }
}
