#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

PHASE="${1:-00}"
branch="dashboard/update-$(date -u +%Y%m%dT%H%M%SZ)"

bash scripts/gates/gate-all.sh "$PHASE"

current_branch="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$current_branch" != "$branch" ]]; then
  git checkout -b "$branch"
fi

git add docs/reports/data/phases docs/reports/data/summary.json docs/reports/data/rtm.json docs/reports/data/tests.json
if git diff --cached --quiet; then
  echo "No dashboard data changes to commit."
  exit 0
fi

git commit -m "chore(dashboard): update quality reports for phase $PHASE"
git push -u origin "$branch"

if command -v gh >/dev/null 2>&1; then
  gh pr create \
    --title "chore(dashboard): update quality reports phase $PHASE" \
    --body "Automated dashboard data update generated by scripts/deploy-dashboard.sh" \
    --base master \
    --head "$branch"
  echo "PR created for dashboard update."
else
  echo "gh CLI not found. Please create a PR manually from $branch to master."
fi
