#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# pre-edit-guard.sh — PreToolUse Hook for Edit|Write
#
# 在 Claude 写入/修改文件之前触发。
# 只做路径级拦截，不解析 tool_input.content（避免依赖不稳定的 JSON 字段）。
#
# 拦截规则：
#   G01. Flyway 迁移文件必须在正确的目录
#   G02. DAG 守卫：模块目录级别的依赖方向
#   G03. 禁止直接修改 Quartz DDL 表（QRTZ_ 表由 Quartz 自管理）
#   G04. 禁止修改锁定文件（pnpm-lock.yaml 应由 pnpm install 生成）
#   G05. 禁止修改 .claude/ 配置（防止 Claude 修改自己的规则）
#   G06. 禁止在错误的 package 中创建前端文件
#
# 通信协议：
#   exit 0  = 允许写入
#   exit 2  = 阻止写入，stderr 内容反馈给 Claude
# ═══════════════════════════════════════════════════════════
set -euo pipefail

INPUT=$(cat)

# 提取文件路径——这是 Edit/Write 工具唯一稳定的字段
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null)

# 如果拿不到路径（理论上不应发生），放行
if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# 标准化路径：去掉开头的 ./ 
FILE_PATH="${FILE_PATH#./}"

# ══════════════════════════════════════════════════════════
# G01: Flyway 迁移文件目录守卫
# ══════════════════════════════════════════════════════════
if [[ "$FILE_PATH" =~ \.sql$ && "$FILE_PATH" =~ (V[0-9]|migration) ]]; then
  EXPECTED_DIR="ljwx-platform-app/src/main/resources/db/migration/"
  if [[ "$FILE_PATH" != ${EXPECTED_DIR}* ]]; then
    echo "BLOCKED [G01]: SQL migration file must be in $EXPECTED_DIR" >&2
    echo "  Attempted path: $FILE_PATH" >&2
    echo "  Move the file to the correct directory." >&2
    exit 2
  fi
fi

# ══════════════════════════════════════════════════════════
# G02: 模块 DAG 守卫
# DAG: core → {security, data} → web → app
# 
# 具体约束：
#   core 模块不能包含引用 security/data/web 的文件
#   security 模块不能包含引用 web 的文件
#   data 模块不能包含引用 security/web 的文件
#   （app 模块可以依赖所有模块）
# ══════════════════════════════════════════════════════════

# core 模块不能创建属于其他模块的文件
if [[ "$FILE_PATH" =~ ^ljwx-platform-core/ ]]; then
  if [[ "$FILE_PATH" =~ /(security|web|controller|filter|interceptor)/ ]]; then
    echo "BLOCKED [G02]: core module must not contain security/web layer code." >&2
    echo "  File: $FILE_PATH" >&2
    echo "  DAG rule: core is the base module, it cannot reference security, data, or web." >&2
    echo "  Move this file to the appropriate module (ljwx-platform-security or ljwx-platform-web)." >&2
    exit 2
  fi
fi

# security 模块不能创建 web 层文件
if [[ "$FILE_PATH" =~ ^ljwx-platform-security/ ]]; then
  if [[ "$FILE_PATH" =~ /(controller|web/controller|rest/)/ ]]; then
    echo "BLOCKED [G02]: security module must not contain controller/REST code." >&2
    echo "  File: $FILE_PATH" >&2
    echo "  DAG rule: security → web, not the reverse. Controllers belong in ljwx-platform-web." >&2
    exit 2
  fi
fi

# data 模块不能创建 security 或 web 层文件
if [[ "$FILE_PATH" =~ ^ljwx-platform-data/ ]]; then
  if [[ "$FILE_PATH" =~ /(security|auth|jwt|controller|web|rest/)/ ]]; then
    echo "BLOCKED [G02]: data module must not contain security or web layer code." >&2
    echo "  File: $FILE_PATH" >&2
    echo "  DAG rule: data module only depends on core. Security and web code belongs elsewhere." >&2
    exit 2
  fi
fi

# ══════════════════════════════════════════════════════════
# G03: 禁止手动创建/修改 Quartz DDL
# Quartz 表由 Quartz 引擎根据配置自动初始化或由官方 DDL 导入
# ══════════════════════════════════════════════════════════
if [[ "$FILE_PATH" =~ \.sql$ ]]; then
  FILE_LOWER=$(echo "$FILE_PATH" | tr '[:upper:]' '[:lower:]')
  if [[ "$FILE_LOWER" =~ qrtz_ && ! "$FILE_LOWER" =~ migration/ ]]; then
    echo "BLOCKED [G03]: Do not manually create Quartz DDL files outside of Flyway migrations." >&2
    echo "  File: $FILE_PATH" >&2
    echo "  Quartz table DDL should be in a Flyway migration file (e.g., V003__init_quartz.sql)." >&2
    exit 2
  fi
fi

# ══════════════════════════════════════════════════════════
# G04: 禁止直接修改生成的锁文件
# ══════════════════════════════════════════════════════════
LOCKED_FILES=(
  "pnpm-lock.yaml"
  "package-lock.json"
  "yarn.lock"
)
for locked in "${LOCKED_FILES[@]}"; do
  if [[ "$FILE_PATH" == *"$locked" ]]; then
    echo "BLOCKED [G04]: Do not directly edit $locked." >&2
    echo "  This file is auto-generated by the package manager." >&2
    echo "  Modify package.json instead, then run 'pnpm install'." >&2
    exit 2
  fi
done

# ══════════════════════════════════════════════════════════
# G05: 禁止修改 .claude/ 配置
# 防止 Claude 在执行过程中修改自己的权限或 hook 配置
# ══════════════════════════════════════════════════════════
if [[ "$FILE_PATH" =~ ^\.claude/ ]]; then
  echo "BLOCKED [G05]: Do not modify .claude/ configuration files during code generation." >&2
  echo "  File: $FILE_PATH" >&2
  echo "  These files control permissions and hooks. They must only be changed by humans." >&2
  exit 2
fi

# ══════════════════════════════════════════════════════════
# G06: 前端文件必须在正确的 package 中
# admin → packages/admin/
# mobile → packages/mobile/
# screen → packages/screen/
# shared → packages/shared/
# ══════════════════════════════════════════════════════════
if [[ "$FILE_PATH" =~ ^ljwx-platform-admin/ ]]; then
  if [[ "$FILE_PATH" =~ \.(vue|ts|tsx)$ ]]; then
    if [[ ! "$FILE_PATH" =~ ^ljwx-platform-admin/packages/ ]]; then
      echo "BLOCKED [G06]: Frontend source files must be inside ljwx-platform-admin/packages/." >&2
      echo "  File: $FILE_PATH" >&2
      echo "  Place it under packages/admin/, packages/mobile/, packages/screen/, or packages/shared/." >&2
      exit 2
    fi
  fi
fi

# ══════════════════════════════════════════════════════════
# 全部通过，允许写入
# ══════════════════════════════════════════════════════════
exit 0
